### ISSUE TITLE
Prepare Todo App

### ISSUE THREAD

**Issue by ayubadiputra** [ayubadiputra/simple-todo-react#1]
Checklist
[] Update readme
[] Update favicon.ico
[] Update index.html

**Comment by ayubadiputra** [comment]
Checklist:
- [x] Update readme
- [x] Update favicon.ico
- [x] Update index.html
- [x] Update index.html
