### ISSUE TITLE
Build Todo App Functionalities

### ISSUE THREAD

**Issue by ayubadiputra** [ayubadiputra/simple-todo-react#4]
The functionalities are including:

- [x] What are the states? Where will they be placed?
- [x] Add new task functionality
- [x] Filter tasks based on the status
- [x] Edit and delete functionalities
